# Generated by Django 5.2 on 2025-05-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loyalty_points',
        ),
    ]
