# Generated by Django 5.2 on 2025-05-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_sale_discount_amount_sale_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
    ]
